### PR TITLE
Add an I2S example

### PR DESCRIPTION
**Pull request by Psirus**
Hello,

I have been trying to get an I2S example to work, and mainly succeeded :) For it to compile, the FreeRTOS.h header needed to be included, so I copied the approach from `src/nesper/esp/task.nim`. The example is basically a slimmed-down version of the [official example](https://github.com/espressif/esp-idf/blob/master/examples/peripherals/i2s/main/i2s_example_main.c) without testing other bitwidths besides 16.

One thing I have noticed is that the channels are reversed, i.e. in the official example the triangle is on the left, and the sine on the right, as I would expect, but in my example it is triangle on the right, sine on the left. This is not what I wanted, but I can't see the error right now. Any ideas?

I wasn't sure what the correct directory structure for examples is; this is what allowed me to get it to compile, let me now if that needs changing. General comments on the code are also appreciated.

### CODE REVIEW

**Comment by elcritch** [comment]
Awesome! I may not get around to checking this out for a couple of days but looking forward to it.

**Comment by elcritch** [comment]
Ok, it looks good. I'm still playing with the examples folders but it's a good place to put an i2s example. What I've been doing is taking the code required to setup a driver like i2c or i2s and making helper functions that are a bit more Nim friendly (like `nesper/driver/i2c.nim` vs `nesper/i2cs.nim`). Eventually it'd be nice to copy the example setup and put it in a `nesper/i2s_utils.nim` file (I'm using the plural for Nim wrappers, or _utils if the plural doesn't work like with `nesper/i2ss.nim`).

**Comment by elcritch** [comment]
I meant to merge this to `devel` branch first.

**Comment by Psirus** [comment]
I totally intend to write a nimified (what is "pythonesque" for nim?) high-level wrapper for this. But I wanted to see if I got this basically right first, and maybe ask if there are additional requirements.

**Pull request merged**
